# Generated by Django 2.1.3 on 2020-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
