# Generated by Django 2.2.10 on 2020-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
